[tool.poetry]
name = "pycaprio"
version = "0.1.1"
description = "Python client for the INCEpTION annotation tool API"
authors = ["Savanamed"]
license = "MIT"
packages = [
    { include = "pycaprio" },
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"
tenacity = "^5.1"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-mock = "*"
requests-mock = "*"
flake8 = "*"
black = { version = "*", allows-prereleases = true }
coverage = "*"
mkdocs = "^1.0"
pytest-cov = "^2.7"
bump2version = "^0.5.11"

[tool.black]
line-length = 120
target_version = ['py36']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
